# Generated by Django 5.1.2 on 2024-10-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_guest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
